### ISSUE TITLE
Não abre a página de finalizar compra

### ISSUE THREAD

**Issue by awakebrasil** [gumnet/magento-2-ame-digital-integration#1]
Bom dia, fiz a instalação, quando vou finalizar a compra não abre a página abre, poderia me ajudar com o que possa ser? 

Att...

**Comment by gumnet** [comment]
Olá ! 

Você já fez o contrato com a AME e inseriu as chaves de integração nas configurações do Magento ?

Se já tiver feito e houver erro poderia me enviar um screenshot do erro que acontece ?

O módulo gera log numa tabela chamada ame_log. Você consegue me enviar as linhas mais recentes deste log ? Mais importante é saber qual o tipo de requisição fez na API e qual erro retornou.

**Comment by gumnet** [comment]
Como não recebemos resposta, estamos dando o caso como fechado. Se voltar a ocorrer por favor abra um novo issue.
