### ISSUE TITLE
Campo endereço no checkout com 3 numeros de linhas

### ISSUE THREAD

**Issue by pedrohenrique1986** [gumnet/magento-2-ame-digital-integration#2]
Encontrei um ajuste necessário no modulo de Magento2 da AME

O módulo só deixa exibir 3 numeros de linhas no endereço no checkout, por exemplo RUA, NUMERO e BAIRRO

Precisa ser usado 4 campos de endereço, por exemplo se o comprador morar em um apartamento, precisa do COMPLEMENTO.

Seria possível realizar essa alteração?

**Comment by gustavoulyssea** [comment]
@pedrohenrique1986 eu acreditava que já existia opção de 5 linhas, mas vou verificar como está, se for viável baseado na API adiciono sim, sem problemas. Volto a te comunicar aqui.

**Comment by pedrohenrique1986** [comment]
Olá @gustavoulyssea percebi que o modulo altera o cadastro no checkout, a grande maioria dos modulos usa o original do Magento2 e pega os valores após preencher, nesse caso voce não precisa enviar o complemento na API da AME e continua funcionando o cadastro como original do Magento2.

Não se fui claro na explicação e se funcionaria.

**Comment by gustavoulyssea** [comment]
Oi Pedro,

Tudo bom ? Eu não entendi bem, mas como está funcionando bem em até alguns grandes players nacionais não sei se vale a pena mexer aí. De qualquer forma, se quiser ajudar em qualquer melhoria, você pode fazer um fork e depois fazer um PR que avaliamos, sendo positivo integramos ao módulo.

Em relação a doc da API ainda não consegui acesso novamente, tendo eu sigo com adição se for possível.

Obrigado!!

**Comment by pedrohenrique1986** [comment]
Oi Gustavo, tranquilo!
Vlw
