### ISSUE TITLE
Cliente não notificado quando o pagamento é aceito

### ISSUE THREAD

**Issue by eaglebr78** [gumnet/magento-2-ame-digital-integration#4]
**Describe the bug**
O cliente não é notificado pelo Magento que o pedido foi aceito. 

**To Reproduce**
1. Entrar no painel admin
2. Entrar em Sales->Orders
3. Escolher um pedido pago no ame
4. Rolar até o fim nos comentários dos pedidos e ver a mensagem de aprovação com customer NOT NOTIFYED

**Expected behavior**
Habilitar no painel de controle da AME uma opção de avisar ao cliente e de mostrar no front.

**Comment by gustavoulyssea** [comment]
Olá @eaglebr78 

Obrigado por aguardar. 

Confirmo que adicionamos o envio por padrão na versão mais atual do módulo.
